// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/lab_03.proto

package lab_03

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadFileRequest) Reset() {
	*x = LoadFileRequest{}
	mi := &file_api_lab_03_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadFileRequest) ProtoMessage() {}

func (x *LoadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lab_03_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadFileRequest.ProtoReflect.Descriptor instead.
func (*LoadFileRequest) Descriptor() ([]byte, []int) {
	return file_api_lab_03_proto_rawDescGZIP(), []int{0}
}

func (x *LoadFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadFileRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type LoadFileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadFileReply) Reset() {
	*x = LoadFileReply{}
	mi := &file_api_lab_03_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadFileReply) ProtoMessage() {}

func (x *LoadFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lab_03_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadFileReply.ProtoReflect.Descriptor instead.
func (*LoadFileReply) Descriptor() ([]byte, []int) {
	return file_api_lab_03_proto_rawDescGZIP(), []int{1}
}

func (x *LoadFileReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAllFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllFilesRequest) Reset() {
	*x = GetAllFilesRequest{}
	mi := &file_api_lab_03_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFilesRequest) ProtoMessage() {}

func (x *GetAllFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lab_03_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFilesRequest.ProtoReflect.Descriptor instead.
func (*GetAllFilesRequest) Descriptor() ([]byte, []int) {
	return file_api_lab_03_proto_rawDescGZIP(), []int{2}
}

type GetAllFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indexed       string                 `protobuf:"bytes,1,opt,name=indexed,proto3" json:"indexed,omitempty"`
	NotIndexed    string                 `protobuf:"bytes,2,opt,name=not_indexed,json=notIndexed,proto3" json:"not_indexed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllFilesResponse) Reset() {
	*x = GetAllFilesResponse{}
	mi := &file_api_lab_03_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFilesResponse) ProtoMessage() {}

func (x *GetAllFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_lab_03_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFilesResponse.ProtoReflect.Descriptor instead.
func (*GetAllFilesResponse) Descriptor() ([]byte, []int) {
	return file_api_lab_03_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllFilesResponse) GetIndexed() string {
	if x != nil {
		return x.Indexed
	}
	return ""
}

func (x *GetAllFilesResponse) GetNotIndexed() string {
	if x != nil {
		return x.NotIndexed
	}
	return ""
}

type FindTermRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Term          string                 `protobuf:"bytes,2,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTermRequest) Reset() {
	*x = FindTermRequest{}
	mi := &file_api_lab_03_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTermRequest) ProtoMessage() {}

func (x *FindTermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lab_03_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTermRequest.ProtoReflect.Descriptor instead.
func (*FindTermRequest) Descriptor() ([]byte, []int) {
	return file_api_lab_03_proto_rawDescGZIP(), []int{4}
}

func (x *FindTermRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FindTermRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

type FindTermResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTermResponse) Reset() {
	*x = FindTermResponse{}
	mi := &file_api_lab_03_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTermResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTermResponse) ProtoMessage() {}

func (x *FindTermResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_lab_03_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTermResponse.ProtoReflect.Descriptor instead.
func (*FindTermResponse) Descriptor() ([]byte, []int) {
	return file_api_lab_03_proto_rawDescGZIP(), []int{5}
}

func (x *FindTermResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_lab_03_proto protoreflect.FileDescriptor

const file_api_lab_03_proto_rawDesc = "" +
	"\n" +
	"\x10api/lab_03.proto\x12\x06lab_03\"?\n" +
	"\x0fLoadFileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\")\n" +
	"\rLoadFileReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x14\n" +
	"\x12GetAllFilesRequest\"P\n" +
	"\x13GetAllFilesResponse\x12\x18\n" +
	"\aindexed\x18\x01 \x01(\tR\aindexed\x12\x1f\n" +
	"\vnot_indexed\x18\x02 \x01(\tR\n" +
	"notIndexed\"A\n" +
	"\x0fFindTermRequest\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04term\x18\x02 \x01(\tR\x04term\",\n" +
	"\x10FindTermResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xd0\x01\n" +
	"\x05Lab03\x12<\n" +
	"\bLoadFile\x12\x17.lab_03.LoadFileRequest\x1a\x15.lab_03.LoadFileReply\"\x00\x12H\n" +
	"\vGetAllFiles\x12\x1a.lab_03.GetAllFilesRequest\x1a\x1b.lab_03.GetAllFilesResponse\"\x00\x12?\n" +
	"\bFindTerm\x12\x17.lab_03.FindTermRequest\x1a\x18.lab_03.FindTermResponse\"\x00B\x1aZ\x18lab_03/pkg/lab_03;lab_03b\x06proto3"

var (
	file_api_lab_03_proto_rawDescOnce sync.Once
	file_api_lab_03_proto_rawDescData []byte
)

func file_api_lab_03_proto_rawDescGZIP() []byte {
	file_api_lab_03_proto_rawDescOnce.Do(func() {
		file_api_lab_03_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_lab_03_proto_rawDesc), len(file_api_lab_03_proto_rawDesc)))
	})
	return file_api_lab_03_proto_rawDescData
}

var file_api_lab_03_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_lab_03_proto_goTypes = []any{
	(*LoadFileRequest)(nil),     // 0: lab_03.LoadFileRequest
	(*LoadFileReply)(nil),       // 1: lab_03.LoadFileReply
	(*GetAllFilesRequest)(nil),  // 2: lab_03.GetAllFilesRequest
	(*GetAllFilesResponse)(nil), // 3: lab_03.GetAllFilesResponse
	(*FindTermRequest)(nil),     // 4: lab_03.FindTermRequest
	(*FindTermResponse)(nil),    // 5: lab_03.FindTermResponse
}
var file_api_lab_03_proto_depIdxs = []int32{
	0, // 0: lab_03.Lab03.LoadFile:input_type -> lab_03.LoadFileRequest
	2, // 1: lab_03.Lab03.GetAllFiles:input_type -> lab_03.GetAllFilesRequest
	4, // 2: lab_03.Lab03.FindTerm:input_type -> lab_03.FindTermRequest
	1, // 3: lab_03.Lab03.LoadFile:output_type -> lab_03.LoadFileReply
	3, // 4: lab_03.Lab03.GetAllFiles:output_type -> lab_03.GetAllFilesResponse
	5, // 5: lab_03.Lab03.FindTerm:output_type -> lab_03.FindTermResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_lab_03_proto_init() }
func file_api_lab_03_proto_init() {
	if File_api_lab_03_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_lab_03_proto_rawDesc), len(file_api_lab_03_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_lab_03_proto_goTypes,
		DependencyIndexes: file_api_lab_03_proto_depIdxs,
		MessageInfos:      file_api_lab_03_proto_msgTypes,
	}.Build()
	File_api_lab_03_proto = out.File
	file_api_lab_03_proto_goTypes = nil
	file_api_lab_03_proto_depIdxs = nil
}
